[server]
maxUploadSize = 1024
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 8501
runOnSave = true
headless = true  # manual open

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
